setattr: setattr.o
	echo "ok"
	gcc -o setattr -lrt setattr.o

createmq.o: createmq.c
	gcc -c -o createmq.o createmq.c

delmq.o: delmq.c
	gcc -c -o delmq.o delmq.c

openmq.o: openmq.c
	gcc -c -o openmq.o openmq.c

sendmq.o: sendmq.c
	gcc -c -o sendmq.o sendmq.c

recvmq.o: recvmq.c
	gcc -c -o recvmq.o recvmq.c

setattr.o: setattr.c
	gcc -c -o setattr.o setattr.c
